Repository raaavioli/ATTACK-AGI, pull requests merged in 2021-10, with the labels that each got.

#37 Character: Squishy
  ATTACK/Assets/Resources/Models/squishy.meta
  ATTACK/Assets/Resources/Models/squishy/Squishy.mat
  ATTACK/Assets/Resources/Models/squishy/Squishy.mat.meta
  ATTACK/Assets/Resources/Models/squishy/Squishy.shader
  ATTACK/Assets/Resources/Models/squishy/Squishy.shader.meta
  ATTACK/Assets/Resources/Models/squishy/SquishyAttack.cs
  ATTACK/Assets/Resources/Models/squishy/SquishyAttack.cs.meta
  ATTACK/Assets/Resources/Models/squishy/SquishyPrefab.prefab
  ATTACK/Assets/Resources/Models/squishy/SquishyPrefab.prefab.meta
  ATTACK/Assets/Resources/Projectiles/Bubble/BubbleMaterial.mat
  ATTACK/Assets/Resources/Projectiles/Bubble/BubblePrefab.prefab
  ATTACK/Assets/Resources/Projectiles/Bubble/BubblePrefab.prefab.meta
  ATTACK/Assets/Resources/Projectiles/Bubble/BubbleShader.shader
  ATTACK/Assets/Resources/Projectiles/Bubble/RainbowTrailMaterial.mat
  ATTACK/Assets/Resources/Projectiles/Bubble/Sphere.prefab
  ATTACK/Assets/Resources/Projectiles/Bubble/Sphere.prefab.meta
  ATTACK/Assets/Scenes/DemoScene.unity
  ATTACK/Assets/Scenes/OliversPlayground.unity
  ATTACK/Assets/Scenes/OliversPlayground.unity.meta
  ATTACK/Assets/Scripts/GameManager.cs
  ATTACK/Assets/Scripts/Projectiles/Attack.cs
  ATTACK/Assets/Scripts/Utils.cs
  ATTACK/UserSettings/EditorUserSettings.asset
Labels: enhancement, graphics

#47 Make python server recognize clubs
  ATTACK/Assets/Prefabs/SpawnPoint/SpawnPoint.prefab
  ATTACK/Assets/Prefabs/SpawnPoint/SpawnPortal.mat
  ATTACK/Assets/Prefabs/SpawnPoint/SpawnPortal.mat.meta
  ATTACK/Assets/Resources/Projectiles/Laser/FlamingLaser.mat
  ATTACK/Assets/Resources/Projectiles/Laser/FreezingLaser.mat.meta
  ATTACK/Assets/Resources/Projectiles/Laser/LaserMaterial.mat
  ATTACK/Assets/Resources/Projectiles/Laser/LaserMaterial.mat.meta
  ATTACK/Assets/Scenes/DemoScene.unity
  ATTACK/Assets/Scripts/CharacterCommon.cs
  ATTACK/Assets/Scripts/Environment/Spawner.cs
  ATTACK/Assets/Scripts/GameManager.cs
  ATTACK/Assets/Scripts/Projectiles/Attack.cs
  ATTACK/Assets/Scripts/Projectiles/LaserAttack.cs
  ATTACK/Assets/Scripts/Projectiles/LightningAttack.cs
  ATTACK/Assets/Scripts/Projectiles/ParticleSystemAttack.cs
  playing-card-detector/python/offlineCvDev.py
  playing-card-detector/python/serverClient.py
  playing-card-detector/sur40screenshots/clubs.png
Labels: enhancement, interaction

#82 create improved terrain and add to scene
  ATTACK/Assets/Prefabs/Terrain/playground.fbx
  ATTACK/Assets/Scenes/DemoScene 1.unity
  External Assets/modeling/environment/playground.blend
  External Assets/modeling/environment/playground.blend1
Labels: art
